\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename analysis_grav.info
@settitle analysis_grav 1.0.0
@c %**end of header
     
@copying
Manual for analysis_grav version 1.0.0
@end copying
     
@titlepage
@title analysis_grav Manual
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
     
@c Output the table of the contents at the beginning.
@contents
     
@ifnottex
@node Top
@top analysis_grav
     
@insertcopying
@end ifnottex
     
@menu
* Introduction:: Summary of features
* Install:: How to install the code
* Input parameters:: Numerical parameters, etc.
* Output results:: CMB results.
@end menu


@node Introduction
@chapter Introduction
 
 analysis_grav is a code to analyse md snapshot by Mario A. Rodriguez-Meza.

@node Install
@chapter Install

./configure

make

make install


@node Input parameters
@chapter Input parameters

See documentation in doc/gravitation/analysis_grav directory.


@node Output results
@chapter Output results

See documentation in doc/gravitation/analysis_grav directory.

@bye
