't" t
.TH simplepofk_rsd_mpi 1 "January 2019" UNIX "NagBody PROJECT"
.na
.nh

.SH NAME
simplepofk_rsd_mpi - computes power spectrum.
.SH SYNOPSIS
\fBsimplepofk_rsd_mpi\fR
.sp

.SH DESCRIPTION
\fBsimplepofk_rsd_mpi\fR - a code to compute power spectrum by Hans A. Winther.

.SH OPTIONS
See documentation in doc/cola/mglpicola directory.
.sp

.SH EXAMPLES
See documentation in doc/cola/mglpicola directory.

.SH SEE ALSO
mglpicola(1)

.SH COPYRIGHT
Copyright (C) 1999-2019
.br
Mario A. Rodriguez-Meza
.br

