\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename planck.info
@settitle planck 1.0.0
@c %**end of header
     
@copying
Manual for planck version 1.0.0
@end copying
     
@titlepage
@title planck Manual
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
     
@c Output the table of the contents at the beginning.
@contents
     
@ifnottex
@node Top
@top planck
     
@insertcopying
@end ifnottex
     
@menu
* Introduction:: Summary of features
* Install:: How to install the code
* Input parameters:: Numerical parameters, etc.
* Output results:: CMB results.
@end menu


@node Introduction
@chapter Introduction
 
planck - public Planck Likelihood Code.


It provides C and Fortran
libraries that allow to compute the log likelihoods of the temperature,
polarization and lensing maps. Optionally, it also provides a python version of
this library, as well as tools to modify the predetermined options for some
likelihoods (changing the high-ell and low-ell lmin and lmax of the temperature).


@node Install
@chapter Install

./configure

make

make install


@node Input parameters
@chapter Input parameters

See documentation in doc/cosmomc_camb/planck directory.


@node Output results
@chapter Output results

See documentation in doc/cosmomc_camb/planck directory.

@bye
