codecov:
  branch: main

fixes:
  # Fix the file names:
  - "/opt/hostedtoolcache/Python/*/x64/lib/python*/site-packages/::"
  - "/Users/runner/hostedtoolcache/Python/*/x64/lib/python*/site-packages/::"

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        enabled: yes
        target: 100%
        threshold: 1%
        branches: null

    patch:
      default:
        target: 100%
        threshold: 1%
        branches: null

  ignore: null

comment: False
