't" t
.TH lpicola 1 "January 2019" UNIX "NagBody PROJECT"
.na
.nh   

.SH NAME
lpicola - COmoving Lagrangian Acceleration (COLA) method.
.SH SYNOPSIS
\fBlpicola\fR
.sp

.SH DESCRIPTION
\fBlpicola\fR - A parallel code for fast dark matter distribution by Cullan Howlett, Marc Manera, Will J. Percival.

An N-body method for solving for Large Scale Structure (LSS) in a frame that is comoving with observers
following trajectories calculated in Lagrangian Perturbation Theory (LPT).

.SH OPTIONS
See documentation in doc/cola/lpicola directory.
.sp

.SH EXAMPLES
See documentation in doc/cola/lpicola directory.

.SH SEE ALSO
cola(1) and mglpicola(1)

.SH COPYRIGHT
Copyright (C) 1999-2019
.br
Mario A. Rodriguez-Meza
.br
